spring:
  application:
    name: recipes
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/recipes
    username: recipes
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: recipes-flyway
    password: ${FLYWAY_PASSWORD}
    placeholders:
      '[db_password]': ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      static-locations: "classpath:/public/,classpath:/static/browser/"
  mvc:
    contentnegotiation:
      media-types:
        woff2: "font/woff2"
